### ISSUE TITLE
Doesn't continue after Steam Guard Check

### ISSUE THREAD

**Issue by xspears81** [Fallout-London/FOLON-FO4Downgrader#11]
Using version 1.5.1

Trying to login using the downgrader, but it keeps looping the Steam Guard verification even if I press allow.

![image](https://github.com/user-attachments/assets/ea8d9230-e24e-4da2-a450-4dd81745f689)

**Comment by DJ3vil** [comment]
Even after Login Successful, and beginning downloading, its ask after Steam Guard in console, but cant type in anything

**Comment by pdg63** [comment]
I have same issue but asks to use my phone app to scan a QR code but there isn't one, you can get a code to copy every 60 seconds but don't where your supposed to post the code, the console is just stuck in a loop. 

Found this fix works from NEXUS Q&A:

Open steam, open the steam directory in the upper left corner.
Go to settings.
Go to security
Click steamguard and disable.

You will also have to disable the guard in your mobile app, the reauthorise it and you will be given a code that you are now asked to enter there is a place to enter said code then it should download and install Fallout London, looks like it takes a while to update.
Hope this helps you out and is not too confusing.

![fall-london](https://github.com/user-attachments/assets/07aa43c1-cd43-4529-b476-556003b09d92)

**Comment by coffandro** [comment]
@xspears81 @DJ3vil Could I get one of you to try version 1.1?

**Comment by githubUser01946** [comment]
> Even after Login Successful, and beginning downloading, its ask after Steam Guard in console, but cant type in anything

Press the (steam)+(x) button to bring up the keyboard, type the password or code and even though it doesnt look like anything appears on screen it is just hidden. The cursor doesnt move but thats a linux thing.

**Comment by coffandro** [comment]
This release might fix the issues with steam guard https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/tag/1.5.3

**Comment by githubUser01946** [comment]
Is it fine to enable steam guard after its done it's downgrading?

**Comment by coffandro** [comment]
This release you *might* be able to just have it on during the entire run but yeah, if it dosen't work then you should enable it like *right* after lol

**Comment by DerValiser** [comment]
Still not working with email codes. If I'd had months to do it, as a developer I'd be extremely embarrassed that people have to disable a security feature here.

**Comment by coffandro** [comment]
Do you want a refund or something?

**Comment by pdg63** [comment]
Unfortunately, I thought I was on a winner with this but after further testing it just fails miserably, I can't justify downloading Fallout 4 just to have it trashed to add the Fallout London I will leave the subject until somehow someone can make it a lot easier to install without turning off the Steam Guard security, thank you all for your efforts.

**Comment by coffandro** [comment]
Tomorrow i will look into changing backend to steamcmd, might fix this since

**Comment by CaelThunderwing** [comment]
the version directly from here worked for me, not teh one on Nexus

**Comment by Reaper948** [comment]
Same issue here, it will just infinitely ask me to verify my Steam Guard and not progress past that.

**Comment by d0nkeyBOB** [comment]
Any luck with a work around instead of disabling steam guard?

**Comment by coffandro** [comment]
Theres a chance the newest release fixes it and i would ask anyone please try it, other than that check out the manual method.

**Comment by DerValiser** [comment]
> Theres a chance the newest release fixes it and i would ask anyone please try it, other than that check out the manual method.

For the life of me, I can't think of any reason why a developer should ask anyone else, let alone strangers, to test something if the developer himself has not agreed to test his code himself.

It would have been easy for you to find a Steam account with Fallout 4 and test it once with mobile or email Steam Guard. You will never have done that. Otherwise it would work. I think I can say that with over 30 years of professional experience.

If you clearly explain what you tested, then I'll be happy to test it again. But not like this.

**Comment by coffandro** [comment]
The reason the last version wasn't working was because it was only me and a handful of other who tested it, and it worksed for us, but it ended up breaking randomly for random people without me being able to *in any way shape or form* recreate the issue, therefore I cannot be the only tester :D

**Comment by Pr0j3ct** [comment]
Can confirm 1.5.4 doesn't solve the steam guard issue

**Comment by pdg63** [comment]
No nate, to be honest, I will wait until it's totally fixed, I am enjoying playing the main Fallout 4 game so it's not that urgent.

Paul D Gutsell

"Care for those that, care about you"

Sent from Proton Mail Android

-------- Original Message --------

**Comment by coffandro** [comment]
> Can confirm 1.5.4 doesn't solve the steam guard issue

Mobile or email?

**Comment by coffandro** [comment]
1.5.4 dosen't work with phone auth, try email auth for that release or wait for the next version

**Comment by coffandro** [comment]
Should be fixed in latest release, please reopen if not
