### ISSUE TITLE
[LINUX] Missing OpenSSL, missing module tkinter despite being installed

### ISSUE THREAD

**Issue by Vibeshibe** [Fallout-London/FOLON-FO4Downgrader#12]
System info:
Manjaro Linux 64 bit
X11 Session

Binary Version: 1.5.1

Output from CLI:
```
curl: /tmp/_MEIUQJgdd/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)
curl: /tmp/_MEIUQJgdd/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)
curl: /tmp/_MEIUQJgdd/libssl.so.3: version `OPENSSL_3.2.0' not found (required by /usr/lib/libcurl.so.4)
curl: /tmp/_MEIUQJgdd/libssl.so.3: version `OPENSSL_3.3.0' not found (required by /usr/lib/libcurl.so.4)
Error in sys.excepthook:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ModuleNotFoundError: No module named 'tkinter'

Original exception was:
Traceback (most recent call last):
  File "FOLON-Downgrader.py", line 927, in <module>
  File "FOLON-Downgrader.py", line 875, in main
  File "FOLON-Downgrader.py", line 49, in SetupFont
  File "zipfile.py", line 1253, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'FOLON-Downgrader-Files/overseer.zip'
[7954] Failed to execute script 'FOLON-Downgrader' due to unhandled exception!
```

Tkinter is installed:
![image](https://github.com/user-attachments/assets/9548eb9b-d878-44c1-81c6-fa112149ff1c)

**Comment by enigmartin** [comment]
Same problem here.
```
$ python --version
Python 3.12.4
$ python -m tkinter
```
Same dialog with version `8.6.13` pops up

**Comment by Shibetendo64** [comment]
exact same issues on my end

System info:
Manjaro Linux 64 bit
X11 Session

Binary Version: 1.5.1

**Comment by FinleyConway** [comment]
The current workaround at the moment is to run it from source. Steps I took:

```git clone https://github.com/Fallout-London/FOLON-FO4Downgrader.git```

```pip install PyQt5```

```cd FOLON-FO4Downgrader```

X11: ```python3 FOLON-Downgrader.py```
Wayland: ```env WAYLAND_DISPLAY=python3 FOLON-Downgrader.py```

**Comment by coffandro** [comment]
I believe the problem is: the downgrader is built on ubuntu 20 so all other distros may have older libraries and such, the solution would be me setting up like 5 vms to build instead

**Comment by thevortexcloud** [comment]
You could also provide a flatpak instead which would avoid that. Ethan Lee also has some advice on packaging for Linux, some of which may be useful.

https://gist.github.com/flibitijibibo/b67910842ab95bb3decdf89d1502de88

**Comment by coffandro** [comment]
TBH the route I might go is just to ship a bash script to run the thing, then people can use that instead of a binary since flatpak is major overkill for this application, appimage is failing and binaries don't work

**Comment by iihmsunn** [comment]
running from ubuntu 24.04 distrobox works around the openssl issue

**Comment by coffandro** [comment]
Could one of you try with the following command?
```
git clone https://github.com/Fallout-London/FOLON-FO4Downgrader.git && cd FOLON-FO4Downgrader && chmod +x && ./Run.sh
```

**Comment by Eldaer** [comment]
> Could one of you try with the following command?
>
> ```
> git clone https://github.com/Fallout-London/FOLON-FO4Downgrader.git && cd FOLON-FO4Downgrader && chmod +x Run.sh && ./Run.sh
> ```

its fine until its done downloading the depot then an error window pops up with this anyone have a solution?;
Traceback (most recent call last): File "/home/user/FOLON-FO4Downgr ader/./FOLON-Downgrader.py", line 35, in run self._Function() File "/home/user/FOLON-FO4Downgr ader/./FOLON-Downgrader.py", line 752, in <lambda> lambda: self.Install(self.DownloadIndex), ^^^^^^ File ^^^^^^^^^^^^^^^^^^^^^^^^^^ "/home/user/FOLON-FO4Downgr ader/./FOLON-Downgrader.py", line 772, in Install self.Wait3() File "/home/user/FOLON-FO4Downgr ader/./FOLON-Downgrader.py", line 784, in Wait3 if self.DownloadIndex == len(self.Depots): ΑΑΑΑΑΑΑΑΑΑΑ AttributeError: 'MainWindow' object has no attribute 'Depots' OK

**Comment by coffandro** [comment]
Yeah that's a weird error with the main branch, I'll merge some new code in about an hour which it'd like one of you to try out, should hopefully just work lol

**Comment by coffandro** [comment]
Hopefully the latest commit should work

**Comment by falconius** [comment]
Im on Nobara (Fedora 40) and im still having issues with this as well.

![image](https://github.com/user-attachments/assets/5b36f6af-e28f-4363-8666-63ef8c4711df)

tried the Run.sh and adjusted it - took me a moment to figure out the comment above.
![image](https://github.com/user-attachments/assets/4a542dea-6e82-4d49-818f-64a81a646385)


it looks like its missing 'PyQt5.QtWinExtras' but im pretty sure i have it.


also getting the same in the executeable:
![image](https://github.com/user-attachments/assets/0bf994c2-5df5-4ebb-b3ae-1a06eef44b82)

**Comment by coffandro** [comment]
Try again now, two merged patches just fixed it, don't use the executable btw, it's getting pulled

**Comment by falconius** [comment]
So far so good! thank you!
now i just gotta try and type my password right :-P

no worries on the executable, i just tried it as part of troubleshooting.

cheers mate!

**Comment by coffandro** [comment]
It seems may be errors on linux #31, I am investigating
