### ISSUE TITLE
Error Manual Download Depot 3

### ISSUE THREAD

**Issue by TGClericOLL** [Fallout-London/FOLON-FO4Downgrader#15]
Recieved error below when downloading "] download_depot 377160 377163 5819088023757897745"

"] download_depot 377160 377163 5819088023757897745
Downloading depot 377163 (18022 MB) ... 
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
src\common\asyncfileiohandler.cpp (260) : !m_bFinishingRequests
src\common\asyncfileiohandler.cpp (260) : !m_bFinishingRequests
src\common\asyncfileiohandler.cpp (260) : !m_bFinishingRequests
src\common\asyncfileiohandler.cpp (260) : !m_bFinishingRequests
src\common\asyncfileiohandler.cpp (260) : !m_bFinishingRequests
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
src\common\crypto_aescbc_openssl.cpp (527) : pubKey
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2"
Depot download failed : error unpacking chunk for file "(�"rogram Files (x86)\Steam\steamapps\content\app_377160\depot_377163\Data\Fallout4 - Textures1.ba2""

The issue I could see being a problem is that my game is in folder E: while its attempting to download into C:. Subsequent download attempts result in error:

"] download_depot 377160 377164 2178106366609958945
Downloading depot 377164 (3243 MB) ... 
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377164\Data\Fallout4 - Voices.ba2"
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377164\Data\Fallout4 - Voices.ba2"
Depot download failed : error writing chunk for "C:\Program Files (x86)\Steam\steamapps\content\app_377160\depot_377164\Data\Fallout4 - Voices.ba2"
CAPIJobRequestUserStats - Server response failed 2"

**Comment by coffandro** [comment]
Do you havw enough storage (about 30 on the driver youre downgrading on?)

**Comment by TGClericOLL** [comment]
> Do you have enough storage (about 40 on the driver youre downgrading on?)

yes 236 gb free on my drive

**Comment by decipher2k** [comment]
Did you start the download twice?

**Comment by coffandro** [comment]
https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/tag/1.5.4 this might fix the issue

**Comment by decipher2k** [comment]
> https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/tag/1.5.4 this might fix the issue

Maybe this is interesting for users who download manually, too. What exactly did you change?
I've got the same error when downloading manually through steam. (Windows 11)

**Comment by coffandro** [comment]
the 1.5.4 release switches the entire backend to steamcmd instead of depotdownloader, should be more reliable

**Comment by decipher2k** [comment]
> the 1.5.4 release switches the entire backend to steamcmd instead of depotdownloader, should be more reliable
i see, thanks. 

i'm sorry for spaming your thread, but it is shown on google when searching for the error :)

for those who have the error when downloading directly from steam:
it happened to me due to the file being locked when downloading. exiting steam, deleting the folder depot_377163 and restarting the download procedure did fix it for me.

**Comment by coffandro** [comment]
If @TGClericOLL could please try that, deleting the folders that crashed and retrying on one of the newer version, otherwise I'm closing due to inacitivty soon
