### ISSUE TITLE
Program looks like someone else is logging into my account

### ISSUE THREAD

**Issue by GnomeBeans** [Fallout-London/FOLON-FO4Downgrader#16]
What is this? Running through linux btw.

![image](https://github.com/user-attachments/assets/9e5f0224-349c-4a28-8a0f-db5a23984ef3)

**Comment by GnomeBeans** [comment]
The interesting part is I didn't get notified on my phone. Removed my steam guard and reset my password. Setup steam guard again and all is fine. Is this an indicator that someone else had access to my account? I had emails and phone verification and the account was accessible so I'm not sure if this was a bug or something else.

**Comment by GnomeBeans** [comment]
This is not me. Could be account be compromised?

**Comment by stoniwankenobii** [comment]
> This is not me. Could my account be compromised?

I believe that is an example picture to show you what the notification will look like on your mobile device with Steam Guard. I had the exact same picture when clicking the info button.

**Comment by GnomeBeans** [comment]
I ended up downloading depots manual. When it failed in the terminal I was very worried and went and updated my steam password XD thanks.

**Comment by stoniwankenobii** [comment]
> I ended up downloading depots manual. When it failed in the terminal I was very worried and went and updated my steam password XD thanks.

No problem, dealing with the OpenSSL issue right now good luck and mind the gap 😏

**Comment by GnomeBeans** [comment]
> > I ended up downloading depots manual. When it failed in the terminal I was very worried and went and updated my steam password XD thanks.
> 
> No problem, dealing with the OpenSSL issue right now good luck and mind the gap 😏

I had openSSL errors in terminal as well but had wayland crash. Try your luck with my method
https://github.com/Fallout-London/FOLON-FO4Downgrader/issues/9
