### ISSUE TITLE
Manually.md missing depots listed on `https://fallout4london.com/release/`

### ISSUE THREAD

**Issue by AlexMonson** [Fallout-London/FOLON-FO4Downgrader#17]
[Manually.md](https://github.com/Fallout-London/FOLON-FO4Downgrader/blob/main/Manually.md) is missing several depots listed on [https://fallout4london.com/release/](https://fallout4london.com/release/) in the "Downgrading Fallout 4 Manually" dropdown of the page. It is not clear if those additional depots are actually required to be rolled back or not.

If they are required then they should be added to Manually.md.

**Comment by jdngray77** [comment]
Maybe that explains why following the guide has bricked my game install several times.

**Comment by coffandro** [comment]
Manually.md assumes you already have Fallout 4 installed and only installs the depots that have been updated by the next gen update

**Comment by AlexMonson** [comment]
@coffandro that's fine, but doesn't the https://fallout4london.com/release/ make the same assumptions? If so then why do the depot lists differ?

**Comment by jdngray77** [comment]
I'm in agreement, surely it would be best for advice and instructions across the brand as a whole to be consistent, without making different assumptions and providing different advice depending on which link you happened to click
