### ISSUE TITLE
Error download

### ISSUE THREAD

**Issue by kile14134** [Fallout-London/FOLON-FO4Downgrader#19]
Unable to download manifest 5698952341602575696 for depot 377162
I cant download all depots.
it just was just constantly Disconnected from Steam

**Comment by coffandro** [comment]
5698952341602575696  dosen't show up in any capacity anywhere in this repo, reopen if issue persists following actual documentation.

**Comment by kile14134** [comment]
> I do not know where you're getting that from? could you send a screenshot?

![QQ_1722012459544](https://github.com/user-attachments/assets/441aa942-746a-4dea-91c1-17dd953f9ef1)
