### ISSUE TITLE
Steam password length/complexity causing error

### ISSUE THREAD

**Issue by gunman121** [Fallout-London/FOLON-FO4Downgrader#21]
I'm not sure exactly what the issue is - but my Steam password is over 60 chars length long, and includes essentially every possible scenario that KeePass allows.

When it asks for my password, I copy and paste it - and it comes back with "Incorrect Auth. Please check your username and password are correct" 

I manually went to Steam, logged in with the exact credentials and it works. 

I tried to re-do this a few times through the downgrader, viewed the password, everything looks the same as it does on the Steam website.

Thanks.

**Comment by coffandro** [comment]
Do you per chance have characters such as " or \ in there?

**Comment by gunman121** [comment]
> Do you per chance have characters such as " or \ in there?

Yes

**Comment by coffandro** [comment]
Alrighty, try adding \ before every instance of those

**Comment by coffandro** [comment]
Im adding a little comment about it in next release
