### ISSUE TITLE
Discrepancy between CLI help and GUI for path

### ISSUE THREAD

**Issue by dakink** [Fallout-London/FOLON-FO4Downgrader#22]
When running FOLON-downgrader without any parameters, the GUI asks for the path to Fallout4.exe

When checking the help it specifies the folder for Steam itself.
`-p , --path    Path to steam(The directory containing a SteamApps folder)`

So when using the -p parameter, files will be put into the regular steamfolder and not Fallout4 folder under SteamLibrary/steamapps/common/Fallout 4 (in my case)

Am I misunderstanding the parameter or is this an oversight perhaps.

**Comment by coffandro** [comment]
This is a documentation issue from a previous version :/ it needs to go to a folder containing Fallout4.exe, will fix in a bit

**Comment by dakink** [comment]
awesome, thanks!
