### ISSUE TITLE
FLON-Downgrader-Files/steam.zip is an empty file

### ISSUE THREAD

**Issue by thomascrha** [Fallout-London/FOLON-FO4Downgrader#29]
This issue is causing the application to loop when you try and login to steam via the downgrader. 

![image](https://github.com/user-attachments/assets/564c5fc5-43b3-4580-8113-6b1851b96e77)

Looking into the issue it seems the file is downloaded and is of 0 size on my system.

![image](https://github.com/user-attachments/assets/2b36ee70-0dab-4401-b6a3-b54ed68ab080)

Will try and investigate the downloading code.

**Comment by thomascrha** [comment]
Fix proposed in #30

**Comment by coffandro** [comment]
Fix merged, don't have a working linux system rn so it's awesome to have community support :D
