### ISSUE TITLE
Unknown failure mode with Fallout 4 downgrader 1.5.3

### ISSUE THREAD

**Issue by ToxiClay** [Fallout-London/FOLON-FO4Downgrader#34]
I was watching a streamer today, and the downgrader was failing in a strange way.

It invoked a command prompt and asked for the streamer's password, but the command prompt wasn't accepting input. I suggested that the input was being masked, as normally happens with password prompts, but the streamer reported that pressing enter wasn't doing anything.

The downgrader window itself stayed at Depot 1/7, and did not indicate that it was waiting for input in another window.

Unfortunately, I have no more information to give, as I was just an observer.

**Comment by coffandro** [comment]
Known issue, old version downloaded from the nexus (We're updating it atm), fixed in 1.5.4/1.5.5
