### ISSUE TITLE
Can't  enter second steam guard code.

### ISSUE THREAD

**Issue by Gnarynhar** [Fallout-London/FOLON-FO4Downgrader#35]
After the first login, the window to enter the steam guard is unreachable for the second code to bet entered. Hoveroing the mouse over the window preview on the taskbar shows it, but there seems to be no way to access it.
And I can't enter the code in through the console window.
![pizdec](https://github.com/user-attachments/assets/697aee96-fb9a-47da-b77c-fe72b444aaba)

**Comment by coffandro** [comment]
Wait this is the old version, if you're submitting bugs to github please check your version coincides with the current one on there (the nexus was outdated until this morning)
