### ISSUE TITLE
BitDefender has a security issue with the Windows .exe file

### ISSUE THREAD

**Issue by JenBauer** [Fallout-London/FOLON-FO4Downgrader#36]
BitDefender has the following error for the Windows executable.  The workaround is to disable BitDefender momentarily to run the file, but it's unclear why it would be flagging this file as a threat.

> We blocked this dangerous page for your protection:
> https://objects.githubusercontent.com/github-production-release-asset-2e65be/804538718/a489cad3-62fd-408c-9efa-2ecd1d635e82?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240804%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240804T151601Z&X-Amz-Expires=300&X-Amz-Signature=1670dbe0b1c2c6699e72ccdbc645c32b9285cee1dd0209fb615e04823942b44a&X-Amz-SignedHeaders=host&actor_id=43556044&key_id=0&repo_id=804538718&response-content-disposition=attachment%3B%20filename%3DFOLON-Downgrader-Windows-x64.zip&response-content-type=application%2Foctet-stream
> Threat name: Gen:Variant.Cerbu.208821
> Dangerous pages attempt to install software that can harm the device, gather personal information or operate without your consent.

![image](https://github.com/user-attachments/assets/e4b682de-8160-4ecf-8ecb-8c3a53ff12b5)

**Comment by coffandro** [comment]
It is flagging it as a threat because we do not have a proper license, we can't do anything about it sadly
