### ISSUE TITLE
Cmd window failed to close on its own towards the end

### ISSUE THREAD

**Issue by JenBauer** [Fallout-London/FOLON-FO4Downgrader#37]
I had a seemingly successful install, but the command window did not close on it's own.  These are the last entries it displayed before I closed it manually.  I'm otherwise able to launch the game, so I'm not sure why this failed.

> Downloading depot 435871
> Validating C:/Program Files (x86)/Steam/steamapps/common/Fallout 4\Data\DLCRobot - Voices_en.ba2
> Validating C:/Program Files (x86)/Steam/steamapps/common/Fallout 4\Data\DLCRobot.esm
>  98.40% C:/Program Files (x86)/Steam/steamapps/common/Fallout 4\Data\DLCRobot - Voices_en.ba2
> 100.00% C:/Program Files (x86)/Steam/steamapps/common/Fallout 4\Data\DLCRobot.esm
> Depot 435871 - Downloaded 3251824 bytes (9060627 bytes uncompressed)
> Total downloaded: 3251824 bytes (9060627 bytes uncompressed) from 1 depots
> Disconnected from Steam
> usage: FOLON-Downgrader.exe [-h] [-p] [-c]
> FOLON-Downgrader.exe: error: unrecognized arguments: Files (x86)/Steam/steamapps/common/Fallout 4

**Comment by coffandro** [comment]
https://github.com/Fallout-London/FOLON-FO4Downgrader/tree/Cleanup

**Comment by coffandro** [comment]
Should be fixed now, will be in 1.5.7
