### ISSUE TITLE
Linux: incorrect case in python script

### ISSUE THREAD

**Issue by redqueenrunning** [Fallout-London/FOLON-FO4Downgrader#39]
App fails in depot 7, with error:
```
Disconnected from Steam
Traceback (most recent call last):
  File "FOLON-Downgrader.py", line 31, in run
  File "FOLON-Downgrader.py", line 766, in RemoveCC
FileNotFoundError: [Errno 2] No such file or directory: '/media/-usr-/-Drive-/SteamLibrary/steamapps/common/Fallout 4/data'
Aborted (core dumped)
```

Two issues. First, this line is not checking self.SteamPath for a trailing "/", and may error on a double "/". Two, the line is using
Lowercase for the Data folder. 
` for i in os.listdir(self.SteamPath + "/data"):`

Workaround for me was to create a symlink for the lowercase version of the folder:
`..../SteamLibrary/steamapps/common/Fallout 4$ ln -s ./Data/ ./data`

**Comment by coffandro** [comment]
This had been fixed for a while, you're on an old version and not using the recommended method (currently broken) of using the script in the readme
