### ISSUE TITLE
Name 'QObject' is not defined

### ISSUE THREAD

**Issue by AftDawn** [Fallout-London/FOLON-FO4Downgrader#44]
Hi, i get the error `NameError: name 'QObject' is not defined. Did you mean: 'object'?`
I know the release says "the final countdown", but you might need just one more fix.

**Comment by coffandro** [comment]
Fixed it a minute after this issue was opened lol

**Comment by thomascrha** [comment]
Hey its a countdown - not the launch. I think its correct we just needed the right import from QT.

**Comment by coffandro** [comment]
Oh no the linux version dosen't need qt at all anymore, was causing too many issues so it's gone over to complete CMD

**Comment by AftDawn** [comment]
> Fixed it a minute after this issue was opened lol

LOL, perfect timing right?

**Comment by coffandro** [comment]
Jup lol
