### ISSUE TITLE
Missing Licence for Depot

### ISSUE THREAD

**Issue by marvyn7** [Fallout-London/FOLON-FO4Downgrader#45]
So, I was trying to get the mod to work, I downloaded my Fo4 from Steam, and tried to follow the Downgrader, I am unable to acess the Steam Guard on the APP because my phone outright refuses to recieve the SMS, so I tried manual, I did as asked, download the depots with the Console, put them in the Fo4 paste, removed Creation Club, but still nothing, no results at all.

I tried them again the downgrader without the Guard option, now I receve the notification that It lacks the License for each depot.

What I do now?

**Comment by coffandro** [comment]
I mean did you have steam guard disable and does the CMD say something about rate limit?

**Comment by marvyn7** [comment]
> I mean did you have steam guard disable and does the CMD say something about rate limit?

I lost the CMD because of a power shortage, but I dont know how to disable the guard, all I know is that no matter how many times i click the sms wont arrive

**Comment by coffandro** [comment]
Well mobile isn't an sms, go to the little help icon to figure out how to do it
