### ISSUE TITLE
Downgrader crashed, now it wants more space

### ISSUE THREAD

**Issue by rpoirier** [Fallout-London/FOLON-FO4Downgrader#47]
The downgrader crashed while I was running it and didn't finish copying over the files it downloaded.
However, now it's trying to start all over from the downloading phase, even though I already have the files.
Is there any way to skip to the copying step? Alternatively, where does it store the files it's downloading so that I can go delete them and start the whole process over. I can't easily free up an additional 28gb of space right now.

**Comment by coffandro** [comment]
It stores them next to fallout 4, in a folder called "SteamFiles", could you post what the error message was or did you not get one? 
Also it is not possible to skip to the step since it probably hasn't finished downloading everything

**Comment by rpoirier** [comment]
I did manage to scrounge up another 28GB and the downgrader picked up where it left off.
Probably not worth the effort on your part to have the disk space check get skipped if it finds all the files already downloaded.

**Comment by coffandro** [comment]
So this is resolved then?
