### ISSUE TITLE
Missing DLC

### ISSUE THREAD

**Issue by Chinthor** [Fallout-London/FOLON-FO4Downgrader#49]
When I began, I had many broken mods and collections on a Next Gen version install, all DLC, no HD Texture update.

In Vortex, I removed and deleted all mods and collections, then ran a file verify in Steam for the Fallout install and all DLC.

I then renamed my Fallout 4 install folder for backup reasons, and made a new empty folder named Fallout 4.

From that blank slate, I followed the instructions for manaul downgrade. All depots were fully downloaded and the contents dumped into the empty Fallout 4 folder. Removed all creation club files and set the app manifest to read only.

When the game is launched via F4SE, I get a perfectly vanilla game lanuch... but Add-ons shows Nuka World is missing. Grayed out and says "coming soon." In Vortex, the nuka plugin .esm files are missing. It shows Fallout4.esm, robot.esm, workshop 1, 2, and 3, and the ccoast.esm. No nuka.

What might have gone wrong? Did I miss something?

**Comment by coffandro** [comment]
The downgrader needs a clean install of fallout 4, it does not download enough files to itself have a full fallout 4 game

**Comment by coffandro** [comment]
Please report back if just installing fallout 4 on steam and then running the downgrader helped.

**Comment by Chinthor** [comment]
Will do. This WAS a full and complete install, if not exactly fresh or clean. As clean as I could make it. Was hoping to avoid a full nuke and pave. Nuking and paving now, will report back after

**Comment by Chinthor** [comment]
I'm repeating the steps found here using a pristine new install. But there is a conflict:
"The downgrader needs a clean install of fallout 4, it does not download enough files to itself have a full fallout 4 game"
If I understand, I need a proper install, then drop all the depot files into it, overwriting as needed.
The guide by Gopher on youtube states the collected Depot files comprise a full and complete install by themselves. The old folder can be archived or deleted. Before I go pointing fingers, is this a genuine conflict? Or am I not comprehending again.
https://www.youtube.com/watch?v=B-s1C3B2qjY&t=45s with notes/instructions in the description. If he got it wrong, he might listen to you more than me.

**Comment by Chinthor** [comment]
This seems to be working. Rebuilding my modlist now. Might be good to drop Gopher a friendly note. Will re-open and add comment if something goes wrong, but otherwise this can probably be closed.

**Comment by coffandro** [comment]
There are issues with Gophers video and we'd have to offer support for that so that's not going to happen.
