### ISSUE TITLE
Keep the Nexus Mods page updated with the latest release

### ISSUE THREAD

**Issue by Pickysaurus** [Fallout-London/FOLON-FO4Downgrader#5]
Hi guys,

Just waiting this to confirm that the Nexus Mods page for this tool is now live. 

Where possible, please try and keep it up to date with the latest version of the tool.

https://www.nexusmods.com/fallout4london/mods/1

Thanks!

**Comment by coffandro** [comment]
We probably will not end up doing this sadly since the plan is to create a "Final" version *very* soon but it's a great idea otherwise
