### ISSUE TITLE
Installation error, zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by IgnisCustos** [Fallout-London/FOLON-FO4Downgrader#50]
After a clean installation on a brand new Win11 system the FOLON downgrader runs into an error stating an errourous zip file. Uppon closer lock it seems steam.zip has a size of 9 bytes and cannot be opened from the system. I tried the FOLON downgrader directly within the "Downloads" folder as well as within the Fallout 4 installation folder to no success. This seams related to issue  #29 but on another OS. 
![2024-10-09_20h19_43](https://github.com/user-attachments/assets/3a616031-88e8-4d93-91ea-252dbc17ddb8)
![2024-10-09_20h41_24](https://github.com/user-attachments/assets/41d64af6-c671-44b4-b93a-02b78e597fe1)

**Comment by coffandro** [comment]
Unzip the files.

**Comment by coffandro** [comment]
Like befordr running

**Comment by IgnisCustos** [comment]
We might be on different levels of understanding. What I did from a game magazine HowTo Guide[1]:  

Presetup
1.a) Downloaded Fallout 4 via Steam
1.b) Downloaded Fallout London via GOG
1.c) Set English as language, deactivate cloud savings

Setup:
2.a) Downloaded the exe from latest release on github [2]
2.b) run program, followed instruction like give path to Fallout 4 Steam install
2.c) put in credentials - submitted 
2.d) Error happened

Only after d) I see a newly created folder called FOLON-Downgrader-Files, in which a steam.zip file with 9 bytes lurks around. I cannot unzip the steam.zip file as seen in the screenshot nor was it there before I first started the downgrader tool. Which zip file are you referring to?


[1] https://www.gamestar.de/artikel/fallout-london-installation-guide,3417028.html#schritt-4-fallout-4-downgraden
[2] https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/tag/1.5.9
![2024-10-10_09h03_56](https://github.com/user-attachments/assets/bb73c97e-a271-4e98-ae85-32aff6ccd226)

**Comment by coffandro** [comment]
Install a clean version of fallout 4, [download the release exe](https://github.com/Fallout-London/FOLON-FO4Downgrader/releases/download/1.5.9/FOLON-Downgrader.exe), run it, follow the prompts.
if it comes with the same error something is wrong with your setup and I would suggest looking into network stability or at least joining the discord for now lol (there's a channel where I might help you quicker) :D

**Comment by IgnisCustos** [comment]
I see, thanks! Fallout 4 was never started on the system.
I just got it working by simply using the latest binary from Nexus Mods. Interesstingly the Nexus Mod version was lower (1.5.8) and also had the mobile authenticator option checkbox. (Screenshots attached)
 
For me this is closed, if someone else come to this thread, try using binaries from Nexus Mod. 

Thanks for the support! Great work so far! 

![2024-10-10_19h28_51](https://github.com/user-attachments/assets/00403a5b-0ae2-4903-8707-6b4fbe1d3cbd)
![2024-10-10_19h30_25](https://github.com/user-attachments/assets/56842061-eb91-467c-bff5-b8d004b3b91d)
