### ISSUE TITLE
Login loop issue

### ISSUE THREAD

**Issue by coffandro** [Fallout-London/FOLON-FO4Downgrader#7]
it loops again and again trying to login

**Comment by jdngray77** [comment]
Mhm, this issue has rate limited and locked me out of steam. Please revise.

**Comment by coffandro** [comment]
It takes about 1-2 hours to get past rollback, I have no idea why this issue arrises so if anyone wants to help, feel free, I'm working on it but the more eyes the easier

**Comment by coffandro** [comment]
Ope, just realised this is the same as #11 but the conversation there's more expansive
